web/router.ex
defmodule Newsline.Router do
  use Newsline.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Newsline do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    resources "/products", ProductController do
      resources "/comments", CommentController, only: [:create]
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", Newsline do
  #   pipe_through :api
  # end
end

lib/newsline/endpoint.ex
defmodule Newsline.Endpoint do
  use Phoenix.Endpoint, otp_app: :newsline

  socket "/socket", Newsline.UserSocket

  # Serve at "/" the static files from "priv/static" directory.
  #
  # You should set gzip to true if you are running phoenix.digest
  # when deploying your static files in production.
  plug Plug.Static,
    at: "/", from: :newsline, gzip: false,
    only: ~w(css fonts images js favicon.ico robots.txt)

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Logger

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Poison

  plug Plug.MethodOverride
  plug Plug.Head

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  plug Plug.Session,
    store: :cookie,
    key: "_newsline_key",
    signing_salt: "xTsKgvgu"

  plug Newsline.Router
end

lib/newsline/repo.ex
defmodule Newsline.Repo do
  use Ecto.Repo, otp_app: :newsline
end

web/models/comment.ex
defmodule Newsline.Comment do
  use Newsline.Web, :model

  schema "comments" do
    field :body, :string
    belongs_to :product, Newsline.Product

    timestamps()
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:body])
    |> validate_required([:body])
  end
end

web/models/product.ex
defmodule Newsline.Product do
  use Newsline.Web, :model

  schema "products" do
    field :title, :string
    field :body, :string
    has_many :comments, Newsline.Comment

    timestamps()
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:title, :body])
    |> validate_required([:title, :body])
  end
end

web/controllers/comment_controller.ex
defmodule Newsline.CommentController do
  use Newsline.Web, :controller
  alias Newsline.Product

  def create(conn, %{"comment" => comment_params, "product_id"=>product_id}) do
    product = Repo.get(Product, product_id)
    comment_changeset = Ecto.build_assoc(product, :comments, body: comment_params["body"])
    Repo.insert(comment_changeset)

    conn
    |> put_flash(:info, "Comment created successfully.")
    |> redirect(to: product_path(conn, :show, product))
  end

end

web/controllers/page_controller.ex
defmodule Newsline.PageController do
  use Newsline.Web, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end
end

web/controllers/product_controller.ex
defmodule Newsline.ProductController do
  use Newsline.Web, :controller

  alias Newsline.{Product, Comment}

  def index(conn, _params) do
    products = Repo.all(Product)
    render(conn, "index.html", products: products)
  end

  def new(conn, _params) do
    changeset = Product.changeset(%Product{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"product" => product_params}) do
    changeset = Product.changeset(%Product{}, product_params)

    case Repo.insert(changeset) do
      {:ok, _product} ->
        conn
        |> put_flash(:info, "Product created successfully.")
        |> redirect(to: product_path(conn, :index))
      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    product = Product
              |>Repo.get(id)
              |>Repo.preload(:comments)
    # product = Repo.get!(Product, id)
    # product = Repo.preload(porduct, :comments)
    comment_changeset = Comment.changeset(%Comment{})
    render(conn, "show.html", product: product, comment_changeset: comment_changeset)
  end

  def edit(conn, %{"id" => id}) do
    product = Repo.get!(Product, id)
    changeset = Product.changeset(product)
    render(conn, "edit.html", product: product, changeset: changeset)
  end

  def update(conn, %{"id" => id, "product" => product_params}) do
    product = Repo.get!(Product, id)
    changeset = Product.changeset(product, product_params)

    case Repo.update(changeset) do
      {:ok, product} ->
        conn
        |> put_flash(:info, "Product updated successfully.")
        |> redirect(to: product_path(conn, :show, product))
      {:error, changeset} ->
        render(conn, "edit.html", product: product, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    product = Repo.get!(Product, id)

    # Here we use delete! (with a bang) because we expect
    # it to always work (and if it does not, it will raise).
    Repo.delete!(product)

    conn
    |> put_flash(:info, "Product deleted successfully.")
    |> redirect(to: product_path(conn, :index))
  end
end

web/views/comment_view.ex
defmodule Newsline.CommentView do
  use Newsline.Web, :view
end

web/views/error_view.ex
defmodule Newsline.ErrorView do
  use Newsline.Web, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Internal server error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

web/views/layout_view.ex
defmodule Newsline.LayoutView do
  use Newsline.Web, :view
end

web/views/page_view.ex
defmodule Newsline.PageView do
  use Newsline.Web, :view
end

web/views/product_view.ex
defmodule Newsline.ProductView do
  use Newsline.Web, :view
end

web/templates/comment/new.html.eex
<h2> Add Your Comment</h2>

<%= form_for @comment_changeset, product_comment_path(@conn, :create, @product), fn f -> %>
    <div class="form-group">
       <%= label f, :body, class: "control-label" %>
       <%= text_input f, :body, class: "form-control" %>
       <%= error_tag f, :body %>
    </div>
    <%= submit "Submit", class: "btn btn-primary" %>
<% end %>

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Newsline!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <nav role="navigation">
          <ul class="nav nav-pills pull-right">
            <li><a href="http://www.phoenixframework.org/docs">Get Started</a></li>
          </ul>
        </nav>
        <span class="logo"></span>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

web/templates/page/index.html.eex
<div class="jumbotron">
  <h2><%= gettext "Welcome to %{name}", name: "Phoenix!" %></h2>
  <p class="lead">Test<br />does not compromise speed and maintainability.</p>
</div>

<div class="row marketing">
  <div class="col-lg-6">
    <h4>Resources</h4>
    <ul>
      <li>
        <a href="http://phoenixframework.org/docs/overview">Guides</a>
      </li>
      <li>
        <a href="https://hexdocs.pm/phoenix">Docs</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix">Source</a>
      </li>
    </ul>
  </div>

  <div class="col-lg-6">
    <h4>Help</h4>
    <ul>
      <li>
        <a href="http://groups.google.com/group/phoenix-talk">Mailing list</a>
      </li>
      <li>
        <a href="http://webchat.freenode.net/?channels=elixir-lang">#elixir-lang on freenode IRC</a>
      </li>
      <li>
        <a href="https://twitter.com/elixirphoenix">@elixirphoenix</a>
      </li>
    </ul>
  </div>
</div>

web/templates/product/edit.html.eex
<h2>Edit product</h2>

<%= render "form.html", changeset: @changeset,
                        action: product_path(@conn, :update, @product) %>

<%= link "Back", to: product_path(@conn, :index) %>

web/templates/product/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :title, class: "control-label" %>
    <%= text_input f, :title, class: "form-control" %>
    <%= error_tag f, :title %>
  </div>

  <div class="form-group">
    <%= label f, :body, class: "control-label" %>
    <%= textarea f, :body, class: "form-control" %>
    <%= error_tag f, :body %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

web/templates/product/index.html.eex
<h2>Listing products</h2>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for product <- @products do %>
    <tr>
      <td><%= product.title %></td>
      <td><%= product.body %></td>

      <td class="text-right">
        <%= link "Show", to: product_path(@conn, :show, product), class: "btn btn-default btn-xs" %>
        <%= link "Edit", to: product_path(@conn, :edit, product), class: "btn btn-default btn-xs" %>
        <%= link "Delete", to: product_path(@conn, :delete, product), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<%= link "New product", to: product_path(@conn, :new) %>

web/templates/product/new.html.eex
<h2>New product</h2>

<%= render "form.html", changeset: @changeset,
                        action: product_path(@conn, :create) %>

<%= link "Back", to: product_path(@conn, :index) %>

web/templates/product/show.html.eex
<h2>Show product</h2>

<ul>

  <li>
    <strong>Title:</strong>
    <%= @product.title %>
  </li>

  <li>
    <strong>Body:</strong>
    <%= @product.body %>
  </li>

</ul>

<%= render Newsline.CommentView, "new.html", conn: @conn, product: @product, comment_changeset: @comment_changeset %>

<ul>
  <%= for comment <- @product.comments do %>
    <li><%= comment.body %></li>
    <% end %>
</ul>
<%= link "Edit", to: product_path(@conn, :edit, @product) %>
<%= link "Back", to: product_path(@conn, :index) %>